services:
  backend:
    build: .
    container_name: sge
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres
    container_name: sge-db
    restart: always
    tty: true
    ports:
      - 5430:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sge-db