services:
  backend:
    build: .
    container_name: sge
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - sge-network
  db:
    image: postgres
    container_name: sge-db
    restart: always
    tty: true
    ports:
      - 5430:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sge-db
    networks:
      - sge-network
  
  redis:
    image: bitnami/redis:latest
    container_name: sge-cache
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=true
    depends_on:
      - backend
    networks:
      - sge-network

networks:
  sge-network:
    driver: bridge