"""introduce-status-profile

Revision ID: 721c2d951a08
Revises: 0c12681e15cf
Create Date: 2025-01-23 10:42:59.396543

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "721c2d951a08"
down_revision: Union[str, None] = "0c12681e15cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("perfis", sa.Column("is_active", sa.Boolean()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("perfis", "is_active")
    # ### end Alembic commands ###
