"""initial

Revision ID: f680c04f5d21
Revises: 
Create Date: 2025-01-15 11:11:40.971492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f680c04f5d21'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizadores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizadores_email'), 'organizadores', ['email'], unique=True)
    op.create_index(op.f('ix_organizadores_id'), 'organizadores', ['id'], unique=False)
    op.create_table('participantes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participantes_email'), 'participantes', ['email'], unique=True)
    op.create_index(op.f('ix_participantes_id'), 'participantes', ['id'], unique=False)
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.Column('organizador_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organizador_id'], ['organizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_id'), 'eventos', ['id'], unique=False)
    op.create_table('participantes_eventos',
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('participante_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evento_id', 'participante_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participantes_eventos')
    op.drop_index(op.f('ix_eventos_id'), table_name='eventos')
    op.drop_table('eventos')
    op.drop_index(op.f('ix_participantes_id'), table_name='participantes')
    op.drop_index(op.f('ix_participantes_email'), table_name='participantes')
    op.drop_table('participantes')
    op.drop_index(op.f('ix_organizadores_id'), table_name='organizadores')
    op.drop_index(op.f('ix_organizadores_email'), table_name='organizadores')
    op.drop_table('organizadores')
    # ### end Alembic commands ###
